### PR TITLE
[IMP] Add "More..." to Related resources widget

### LINKED ISSUE #375: Add link to "More..." to view more resources
- Add the option to display `More...` on the top or bottom of the widget section.
- Provide the field for the user to include the redirect link for `More...`

### PR DESCRIPTION
**Pull request by S-mardii**
Fixed #375

### CODE REVIEW

**Comment by S-mardii** [comment]
Is this on PP now?

**Comment by EricSoroos** [comment]
@S-mardii I've done the branch re-org now: the Default branch is now `main` (to match github's new standard layout), `master` has been renamed to `master-old`.  We're going to abandon the php7 branch name, as it should have been done years back.

**Comment by S-mardii** [comment]
Noted with thanks.

**Comment by S-mardii** [comment]
@EricSoroos is this on Prod yet?

**Pull request merged**
