### PR TITLE
Created a new function to get dataset ID from url. Updated the download link

### LINKED ISSUE #174: Update download link in toggle information of layer in Map explorer
screenshot_9

### PR DESCRIPTION
**Pull request by Huyeng**
Fixes #174

### CODE REVIEW

**Comment by acorbi** [comment]
@Huyeng Before we merge this PR, I want to ask you for a last thing:

As you can see  on my last commit https://github.com/OpenDevelopmentMekong/wpckan/pull/175/commits/7f35a328c34d4bfd45868a92f5f90fb8fcc04570, I have added some test cases for ensuring that the function you have created is solid. In those tests, I am covering situations that I believe could happen.

Please, modify the function so the test cases are ALL passing in order to merge this PR. 

Also, I moved the new function from **wpckan-api.php**, to **wpckan-utils.php**, since it is a utility function and not a function related to the API.

**Comment by Huyeng** [comment]
OK. I will check it soon.

**Comment by Huyeng** [comment]
I think the test function that you created it looks fine.

**Comment by acorbi** [comment]
@Huyeng Are ALL the tests passing for you? If you run ```phpunit tests/``` which output do you get?

**Comment by Huyeng** [comment]
Well, just test it, errors occurred as below:
Result Test:
................SS.S.....E.F                                      28 / 28 (100%)
Time: 3.86 seconds, Memory: 10.50MB
There was 1 error:
1) UtilsTest::testGetDatasetIdFromUrlAnotherType
Undefined offset: 1
D:\www\ODM\wp-content\plugins\wpckan\utils\wpckan-utils.php:206
D:\www\ODM\wp-content\plugins\wpckan\tests\UtilsTest.php:171
--
There was 1 failure:
1) UtilsTest::testGetDatasetIdFromUrlTwoParams
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'123456?another_param=some_value'
+'123456'

D:\www\ODM\wp-content\plugins\wpckan\tests\UtilsTest.php:184

ERRORS!
Tests: 28, Assertions: 24, Errors: 1, Failures: 1, Skipped: 3.

**Comment by acorbi** [comment]
Exactly, so as I said above:

> Please, modify the function so the test cases are ALL passing in order to merge this PR.

If you have any question, please ping me on gitter.

**Comment by acorbi** [comment]
ok, tests are now passsing, merging....

**Pull request merged**
